In [3]:
import itertools
import numpy as np
import torch

In [4]:
item = [1,2,3,4]

In [6]:
for x in itertools.combinations_with_replacement(item,3):
    print(x)

(1, 1, 1)
(1, 1, 2)
(1, 1, 3)
(1, 1, 4)
(1, 2, 2)
(1, 2, 3)
(1, 2, 4)
(1, 3, 3)
(1, 3, 4)
(1, 4, 4)
(2, 2, 2)
(2, 2, 3)
(2, 2, 4)
(2, 3, 3)
(2, 3, 4)
(2, 4, 4)
(3, 3, 3)
(3, 3, 4)
(3, 4, 4)
(4, 4, 4)


In [11]:
out = torch.combinations(torch.tensor(item),with_replacement=True,r=3)

In [16]:
(out==1).sum(axis=1)

tensor([3, 2, 2, 2, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [43]:
dims = [1,2,3]
p = 3

terms = []
for order in range(p+1):
    for x in itertools.combinations_with_replacement(dims,order):
        terms.append(np.array(x))
terms = np.array(terms)
print(terms)

[array([], dtype=float64) array([1]) array([2]) array([3]) array([1, 1])
 array([1, 2]) array([1, 3]) array([2, 2]) array([2, 3]) array([3, 3])
 array([1, 1, 1]) array([1, 1, 2]) array([1, 1, 3]) array([1, 2, 2])
 array([1, 2, 3]) array([1, 3, 3]) array([2, 2, 2]) array([2, 2, 3])
 array([2, 3, 3]) array([3, 3, 3])]


In [44]:
def convert_terms(terms,dims):
    out = np.zeros([len(terms),len(dims)])
    for i,term in enumerate(terms):
        for j, dim in enumerate(dims):
            out[i,j] = (term==dim).sum()
    return out

In [48]:
out = convert_terms(terms,dims)

In [49]:
out

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [2., 0., 0.],
       [1., 1., 0.],
       [1., 0., 1.],
       [0., 2., 0.],
       [0., 1., 1.],
       [0., 0., 2.],
       [3., 0., 0.],
       [2., 1., 0.],
       [2., 0., 1.],
       [1., 2., 0.],
       [1., 1., 1.],
       [1., 0., 2.],
       [0., 3., 0.],
       [0., 2., 1.],
       [0., 1., 2.],
       [0., 0., 3.]])

In [50]:
len(out)

20

In [19]:
torch.tensor()

TypeError: tensor() missing 1 required positional arguments: "data"