In [21]:
import itertools
import numpy as np

In [43]:
dims = [1,2,3]
p = 3

terms = []
for order in range(p+1):
    for x in itertools.combinations_with_replacement(dims,order):
        terms.append(np.array(x))
terms = np.array(terms)
print(terms)

[array([], dtype=float64) array([1]) array([2]) array([3]) array([1, 1])
 array([1, 2]) array([1, 3]) array([2, 2]) array([2, 3]) array([3, 3])
 array([1, 1, 1]) array([1, 1, 2]) array([1, 1, 3]) array([1, 2, 2])
 array([1, 2, 3]) array([1, 3, 3]) array([2, 2, 2]) array([2, 2, 3])
 array([2, 3, 3]) array([3, 3, 3])]


In [44]:
def convert_terms(terms,dims):
    out = np.zeros([len(terms),len(dims)])
    for i,term in enumerate(terms):
        for j, dim in enumerate(dims):
            out[i,j] = (term==dim).sum()
    return out

In [48]:
out = convert_terms(terms,dims)

In [49]:
out

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [2., 0., 0.],
       [1., 1., 0.],
       [1., 0., 1.],
       [0., 2., 0.],
       [0., 1., 1.],
       [0., 0., 2.],
       [3., 0., 0.],
       [2., 1., 0.],
       [2., 0., 1.],
       [1., 2., 0.],
       [1., 1., 1.],
       [1., 0., 2.],
       [0., 3., 0.],
       [0., 2., 1.],
       [0., 1., 2.],
       [0., 0., 3.]])

In [50]:
len(out)

20