In [1]:
import os
home = os.getenv("HOME")
os.chdir(home+"/codes/pymfree/")

In [2]:
import torch 
from pymfree.util.utils import insert_A_in_AP_matrix
from pymfree.util.utils import asymmetric_distances
from pymfree.util.utils import symmetrise_AP
from pymfree.core.function import L2Norm

In [3]:
norm = L2Norm()

In [4]:
x = torch.rand(4,3)

In [5]:
diff = asymmetric_distances(x)

In [6]:
diff

tensor([[ 0.8126, -0.6735,  0.3447],
        [-0.1283, -0.8331,  0.0822],
        [ 0.5632, -0.4720,  0.2952],
        [-0.9409, -0.1596, -0.2626],
        [-0.2494,  0.2015, -0.0495],
        [ 0.6915,  0.3611,  0.2131]])

In [7]:
scalar = norm(diff) 

In [8]:
scalar

tensor([1.1103, 0.8469, 0.7919, 0.9898, 0.3244, 0.8087])

In [9]:
my_try = torch.rand(2,1,6)

In [14]:
my_try

tensor([[[0.8491, 0.2638, 0.6330, 0.4111, 0.2552, 0.8317]],

        [[0.4687, 0.4466, 0.9155, 0.0923, 0.0989, 0.8026]]])

In [11]:
AP = torch.zeros(2,1,8,8)

In [12]:
AP = insert_A_in_AP_matrix(my_try,AP,4)

torch.Size([2, 1, 3])
torch.Size([2, 1, 3]) 0 3
torch.Size([2, 1, 2])
torch.Size([2, 1, 2]) 3 5
torch.Size([2, 1, 1])
torch.Size([2, 1, 1]) 5 6


In [13]:
AP

tensor([[[[0.0000, 0.8491, 0.2638, 0.6330, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.4111, 0.2552, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.8317, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000]]],


        [[[0.0000, 0.4687, 0.4466, 0.9155, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0923, 0.0989, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.8026, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        

In [16]:
AP = AP + AP.transpose(2,3)

In [17]:
AP

tensor([[[[0.0000, 0.8491, 0.2638, 0.6330, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.8491, 0.0000, 0.4111, 0.2552, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.2638, 0.4111, 0.0000, 0.8317, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.6330, 0.2552, 0.8317, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000]]],


        [[[0.0000, 0.4687, 0.4466, 0.9155, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.4687, 0.0000, 0.0923, 0.0989, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.4466, 0.0923, 0.0000, 0.8026, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.9155, 0.0989, 0.8026, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        