In [1]:
import os
home = os.getenv("HOME")
os.chdir(home+"/codes/pymfree/")

In [2]:
from pymfree.core.derivative import derivative_parser
from pymfree.core.derivative import derivative_component_parser

In [3]:
parsing = "kjasdkj__34  m+$3  .141(   1,2)2(1,1,2,2)-3.5(3,3,3)$ksd$lksd"

In [4]:
sig, comp_sigs = derivative_parser(parsing)

In [5]:
comp_sigs[0]

'3.141(1,2)'

In [6]:
comp_sig, factor, indices = derivative_component_parser(comp_sigs[0])

In [7]:
indices

[1, 2]

In [17]:
for element in indices:
    element = int(element)

In [20]:
list(map(int,indices))

[1, 2]

In [2]:
parsing.count("$")

3

In [3]:
parsing.partition("$")

('kjasdkj__34m+', '$', '3.141(1,2)2(1,1,2,2)-3.5(3,3,3)$ksd$lksd')

In [4]:
parsing.strip()

'kjasdkj__34m+$3.141(1,2)2(1,1,2,2)-3.5(3,3,3)$ksd$lksd'

In [5]:
parsing.split('$')[1]

'3.141(1,2)2(1,1,2,2)-3.5(3,3,3)'

In [6]:
signature = parsing.strip().split('$')[1].strip()

In [7]:
signature

'3.141(1,2)2(1,1,2,2)-3.5(3,3,3)'

In [8]:
signature.count('(') == signature.count(')')

True

In [21]:
def component_extract(input):

    brackets = []
    brackets.append(input[0:input.find(')')+1].strip())
    temp = input[input.find(')')+1:].strip()
    index = temp.find('(')
    while index > 0:
        prob = temp[0:index]
        brackets.append(temp[0:temp.find(')')+1])
        temp = temp[temp.find(')')+1:].strip()
        index = temp.find('(')
    return brackets

In [22]:
component_extract(signature)

['3.141(1,2)', '2(1,1,2,2)', '-3.5(3,3,3)']

In [11]:
x

NameError: name 'x' is not defined

In [12]:
float('-3.5')

-3.5

In [13]:
parsing

'kjasdkj__34m+$3.141(1,2)2(1,1,2,2)-3.5(3,3,3)$ksd$lksd'

In [14]:
parsing.encode().find('$')

TypeError: argument should be integer or bytes-like object, not 'str'

In [15]:
x = '-3.5'

In [16]:
float(x.encode())

-3.5

In [17]:
'-' == '-'

True

In [23]:
test = "slksd dsd   slksdlk3k  93484   s"

In [24]:
test = test.replace(' ','')

In [25]:
test

'slksddsdslksdlk3k93484s'

In [8]:
import numpy as np

In [14]:
x = np.random.randint(0,10,size=10)

In [15]:
x

array([6, 4, 9, 0, 6, 5, 6, 7, 3, 5])

In [18]:
for number in np.unique(x):
    print(np.count)

0
3
4
5
6
7
9


In [27]:
test = np.stack(np.unique(x,return_counts=True),axis=-1)

In [28]:
test

array([[0, 1],
       [3, 1],
       [4, 1],
       [5, 2],
       [6, 3],
       [7, 1],
       [9, 1]])

In [ ]:
x

In [29]:
np.m(test)

(7, 2)

In [30]:
test[-1,0]

9

In [34]:
np.sum(test[:,1])

10

In [43]:
import torch
torch.randint(10,(10,)).dtype

torch.int64

In [51]:
test2 = torch.zeros(10,dtype=int)

In [55]:
for line in test:
    test2[line[0]] = torch.from_numpy(line)[1]

In [59]:
test2

tensor([1, 0, 0, 1, 1, 2, 3, 1, 0, 1])

In [58]:
len(test)

7

In [60]:
4!

SyntaxError: invalid syntax (<ipython-input-60-d8241d4edda9>, line 1)

In [61]:
np.factorial()

AttributeError: module 'numpy' has no attribute 'factorial'

In [62]:
np.math.factorial(3)

6

In [63]:
out = 2.
for line in test:
    out *= np.math.factorial(line[1])

In [64]:
out

24.0

In [67]:
len(test2.shape)

1

In [68]:
print("Signature")
print("---------")

Signature
---------
