In [43]:
import os
home = os.getenv("HOME")
os.chdir(home+"/codes/pymfree/")

In [44]:
import torch
import numpy as np
import sklearn
from sklearn.neighbors import DistanceMetric
import pymfree.core.functional as F
from pymfree.core.norm import Norm
from pymfree.core.norm import L2Norm

## Norm Definitions and Timing

In [3]:
x1 = torch.rand(100000,3)
x2 = torch.rand(100000,3)
x3 = np.random.rand(100000,3)
x4 = np.random.rand(100000,3)

In [4]:
len(x1.shape)

2

In [5]:
%%time
result = F.l2(x1)

CPU times: user 2.09 ms, sys: 3.65 ms, total: 5.74 ms
Wall time: 1.83 ms


In [6]:
%%time 
result = F.l2(x1-x2)

CPU times: user 5.38 ms, sys: 0 ns, total: 5.38 ms
Wall time: 1.24 ms


In [7]:
l2_skl = DistanceMetric.get_metric('euclidean')
point = [0.,0.,0.]
ref = np.empty((1,3))
ref[0] = point

In [8]:
%%time 
result = l2_skl.pairwise(x3-x4,ref)

CPU times: user 2.93 ms, sys: 627 µs, total: 3.56 ms
Wall time: 2.73 ms


In [9]:
my_norm = L2Norm()

In [10]:
%%time
result = my_norm.NoChecksPair(x1,x2)

CPU times: user 4.36 ms, sys: 815 µs, total: 5.17 ms
Wall time: 1.12 ms


In [11]:
type(result)

torch.Tensor

In [12]:
%%time
my_norm.array_out = True
result = my_norm(x3,x4)

CPU times: user 17.6 ms, sys: 0 ns, total: 17.6 ms
Wall time: 4.18 ms


In [13]:
metric = sklearn.neighbors.DistanceMetric.get_metric('pyfunc',func=my_norm.sklearn_dist)

In [14]:
%%time
result = metric.pairwise(x3-x4, ref)

CPU times: user 4.25 s, sys: 0 ns, total: 4.25 s
Wall time: 4.25 s


In [19]:
result

array([[0.6762106 ],
       [0.48675421],
       [0.66289467],
       ...,
       [0.81493543],
       [0.86552196],
       [0.50522523]])

In [16]:
my_norm.sklearn_dist(x1,ref)

TypeError: PyMFree Norm: Need torch Tensor of shape (n,d).

In [17]:
x5 = np.random.rand(3)
x6 = np.random.rand(3)

In [18]:
my_norm.sklearn_dist(x5,x6)

array(1.05026461)

In [22]:
isinstance(my_norm, L2Norm)

True

In [23]:
x = torch.rand(10,10,10)

In [28]:
for line in x:
    print(line.shape)

torch.Size([10, 10])
torch.Size([10, 10])
torch.Size([10, 10])
torch.Size([10, 10])
torch.Size([10, 10])
torch.Size([10, 10])
torch.Size([10, 10])
torch.Size([10, 10])
torch.Size([10, 10])
torch.Size([10, 10])


In [15]:
def test_f(x):
    return x.shape

In [22]:
try:
    test_f(torch.rand(10), torch.rand(8))
except Exception as e:
    print(e)

test_f() takes 1 positional argument but 2 were given


In [8]:
r = torch.rand(10)

In [9]:
torch.exp(-torch.pow(r, 2))

tensor([0.5141, 0.9239, 0.9965, 0.9999, 0.5335, 0.9941, 0.4266, 0.5710, 0.9744,
        0.4943])

In [11]:
torch.tensor(0).shape

torch.Size([])

In [12]:
mine = {'test' : 1, 'test2' : 2.}

In [13]:
mine

{'test': 1, 'test2': 2.0}

In [14]:
mine.values()

dict_values([1, 2.0])

In [ ]:
for key, x in mine.values()


In [16]:
test3 =[]
test4= []

In [33]:
test3, test4 = zip(*[(key,x) for key, x in mine.items()])

In [21]:
for key, value in mine.values():
    print(key)

TypeError: cannot unpack non-iterable int object

In [22]:
mine

{'test': 1, 'test2': 2.0}

In [24]:
test3

[1, 2.0]

In [29]:
test3

('test', 1)

In [35]:
test4

(1, 2.0)

In [37]:
type(torch.device('cpu'))

torch.device

In [38]:
x = torch.rand(30)

In [40]:
x = x.to(torch.device('cpu'))

In [41]:
x

tensor([0.7993, 0.6759, 0.2407, 0.9368, 0.2786, 0.1179, 0.2627, 0.7775, 0.9536,
        0.2038, 0.8492, 0.4192, 0.5474, 0.7776, 0.8183, 0.5241, 0.6989, 0.6648,
        0.8443, 0.1373, 0.1285, 0.0577, 0.5034, 0.8627, 0.2614, 0.9515, 0.9469,
        0.5260, 0.6852, 0.3917])

In [42]:
x.device

device(type='cpu')

In [45]:
class fake_class(object):
    def __init__(self):
        self.name = self.__class__.__name__

    def __str__(self):
        return str(self.name)
    def __repr__(self):
        print(self)

In [46]:
my_class = fake_class

In [47]:
print(fake_class)

<class '__main__.fake_class'>


In [57]:
x = fake_class

In [50]:
def my_func():
    return 4

In [54]:
my_func.__class__.__name__

'function'

In [55]:
x =str(my_func)[]

In [56]:
x

'<function my_func at 0x7fdfca07f680>'

In [61]:
x = str(x)

In [62]:
type(x)

str

In [70]:
one = x[x.rfind('.')+1:x.rfind('\'')]

In [71]:
two = str(my_func).split(' ')[1]

In [76]:
final = one + "\n\n" +two

In [77]:
print(final)

fake_class

my_func


In [78]:
test = {'one' : 1, 'two' : 2}

In [79]:
str(test)

"{'one': 1, 'two': 2}"

In [80]:
test.values()

dict_values([1, 2])

In [81]:
x = list(test.values())
y = list(test.keys())

In [82]:
x

[1, 2]

In [86]:
x2 = torch.rand(2)

In [84]:
y = t

['one', 'two']

In [88]:
{key: value for (key,value) in zip(y,x2)}

{'one': tensor(0.2945), 'two': tensor(0.9416)}

In [89]:
isinstance(x2, torch.Tensor)

True

In [91]:
isinstance(y, list)

True