In [9]:
import torch
import numpy as np

## Norm Definitions and Timing

In [10]:
x1 = torch.rand(10000,3)
x2 = torch.rand(10000,3)

In [11]:
def f1(x1,x2):
    return torch.sqrt(torch.sum(torch.pow(x1-x2,2),axis=1))

class norm1(object):
    """
    This is a docstring.
    """
    def __init__(self,F):
        if not callable(F):
            raise TypeError("PyMFree Norm: Function not callable")
        self.F = F

    def __call__(self,x1,x2=None):
        pass

    def NoChecksPair(self,x1,x2):
        return self.F(x1,x2)

In [12]:
def f2(x):
    return torch.sqrt(torch.sum(torch.pow(x,2),axis=1))

class norm2(object):
    """
    This is a docstring.
    """
    def __init__(self,F):
        if not callable(F):
            raise TypeError("PyMFree Norm: Function not callable")
        self.F = F

    def __call__(self,x1,x2=None):
        pass

    def NoChecksPair(self,x1,x2):
        return self.F(x1-x2)

In [36]:
def f3(x):
    return torch.sqrt(torch.sum(x*x,axis=1))

In [13]:
my_norm = norm1(f1)
my_norm2 = norm2(f2)

In [31]:
%%time 
f1(x1,x2)

CPU times: user 1.58 ms, sys: 0 ns, total: 1.58 ms
Wall time: 781 µs


tensor([0.6852, 0.6985, 1.3004,  ..., 0.1676, 0.7681, 1.1274])

In [52]:
%%time
f2(x1-x2)

CPU times: user 1.54 ms, sys: 133 µs, total: 1.67 ms
Wall time: 767 µs


tensor([0.6852, 0.6985, 1.3004,  ..., 0.1676, 0.7681, 1.1274])

In [73]:
%%time
f3(x1-x2)

CPU times: user 2.15 ms, sys: 0 ns, total: 2.15 ms
Wall time: 1.19 ms


tensor([0.6852, 0.6985, 1.3004,  ..., 0.1676, 0.7681, 1.1274])

In [65]:
%%time 
torch.dist(x1,x2)

CPU times: user 2.02 ms, sys: 48 µs, total: 2.07 ms
Wall time: 902 µs


tensor(70.2403)

In [59]:
%%time 
torch.pairwise_distance(x1,x2)

CPU times: user 7.11 ms, sys: 0 ns, total: 7.11 ms
Wall time: 5.53 ms


tensor([0.6852, 0.6985, 1.3004,  ..., 0.1676, 0.7681, 1.1274])

In [52]:
%%time
my_norm.NoChecksPair(x1,x2)

CPU times: user 2.89 ms, sys: 112 µs, total: 3 ms
Wall time: 1.66 ms


tensor([0.7760, 0.5958, 0.5961,  ..., 0.1810, 0.9821, 0.8875])

## RBFs and timing