In [1]:
import torch
import numpy as np

In [6]:
torch.current_device()

AttributeError: module 'torch' has no attribute 'current_device'

In [7]:
torch.device('cpu')

device(type='cpu')

In [9]:
x =torch.rand((10,3))

In [10]:
x[0]

tensor([0.8564, 0.2552, 0.8705])

In [11]:
ref = torch.rand(1,3)

In [12]:
x - ref

tensor([[ 0.7118, -0.1973,  0.4388],
        [ 0.0900,  0.5144,  0.4334],
        [ 0.3662,  0.1302,  0.4984],
        [ 0.3605, -0.2682, -0.4023],
        [ 0.4175,  0.5001, -0.3299],
        [ 0.4785, -0.3132, -0.4084],
        [ 0.5098, -0.0322,  0.1477],
        [-0.0243,  0.5328,  0.1293],
        [ 0.2912,  0.2004,  0.5180],
        [ 0.7245,  0.1096,  0.2939]])

In [20]:
torch.sqrt(torch.sum(torch.pow(x-ref,2),axis=1,keepdim=True))

tensor([[0.8592],
        [0.6786],
        [0.6320],
        [0.6031],
        [0.7303],
        [0.7027],
        [0.5317],
        [0.5488],
        [0.6271],
        [0.7895]])

In [23]:
len(torch.empty(0))

0

In [32]:
x = {'one' : 1, 'two' :2}

In [34]:
for key,value  in x.items():
    print(key) 

one
two


In [35]:
test = torch.empty(0)

In [37]:
test.append(3)

AttributeError: 'Tensor' object has no attribute 'append'

In [39]:
test = torch.cat((test,3.),dim=0)

TypeError: expected Tensor as element 1 in argument 0, but got float

In [40]:
yada = [3,2,3,4]

In [41]:
torch.Tensor(yada)

tensor([3., 2., 3., 4.])

In [42]:
x

{'one': 1, 'two': 2}

In [46]:
x.values()

dict_values([1, 2])

In [48]:
torch.Tensor(x.values())

TypeError: new(): data must be a sequence (got dict_values)