In [1]:
import torch
import numpy as np

## Timing

In [2]:
x1 = torch.rand(10000,3)
x2 = torch.rand(10000,3)

In [3]:
def f(x1,x2):
    return torch.sqrt(torch.sum(torch.pow(x1-x2,2),axis=1))

class norm(object):
    """
    This is a docstring.
    """
    def __init__(self,F):
        if not callable(F):
            raise TypeError("PyMFree Norm: Function not callable")
        self.F = F

    def __call__(self,x1,x2=None):
        pass

    def NoChecksPair(self,x1,x2):
        return self.F(x1,x2)

In [4]:
my_norm = norm(f)

In [7]:
%%time 
f(x1,x2)

CPU times: user 2.75 ms, sys: 372 µs, total: 3.12 ms
Wall time: 1.6 ms


tensor([0.8796, 0.6421, 0.5602,  ..., 0.3806, 0.4741, 0.7938])

In [9]:
%%time 
torch.dist(x1,x2)

CPU times: user 5.13 ms, sys: 156 µs, total: 5.29 ms
Wall time: 2.89 ms


tensor(70.7821)

In [11]:
%%time 
torch.pairwise_distance(x1,x2)

CPU times: user 13.4 ms, sys: 4.16 ms, total: 17.5 ms
Wall time: 13.7 ms


tensor([0.8796, 0.6421, 0.5602,  ..., 0.3806, 0.4741, 0.7938])

In [52]:
%%time
my_norm.NoChecksPair(x1,x2)

CPU times: user 2.89 ms, sys: 112 µs, total: 3 ms
Wall time: 1.66 ms


tensor([0.7760, 0.5958, 0.5961,  ..., 0.1810, 0.9821, 0.8875])

In [59]:
y=torch.cdist(x1,x2)

In [62]:
torch.sort(y,axis=1)

torch.return_types.sort(
values=tensor([[0.0168, 0.0333, 0.0417,  ..., 1.2878, 1.3032, 1.3160],
        [0.0458, 0.0462, 0.0625,  ..., 1.1436, 1.1519, 1.1585],
        [0.0405, 0.0406, 0.0420,  ..., 1.1753, 1.1798, 1.2053],
        ...,
        [0.0316, 0.0341, 0.0418,  ..., 1.2637, 1.2652, 1.2960],
        [0.0207, 0.0256, 0.0282,  ..., 1.4104, 1.4117, 1.4157],
        [0.0149, 0.0362, 0.0407,  ..., 1.1309, 1.1381, 1.1647]]),
indices=tensor([[ 808, 1521, 8984,  ..., 3119, 7862, 4176],
        [3104, 7361, 2684,  ..., 7862, 4176, 1739],
        [9380, 5874, 3976,  ..., 6813, 9765, 1739],
        ...,
        [3688, 2969, 4148,  ..., 9238, 7306, 6725],
        [8129,  860, 3507,  ...,  859, 8217, 3034],
        [ 257, 7006, 8441,  ..., 7306, 2322, 6725]]))

In [6]:
torch.current_device()

AttributeError: module 'torch' has no attribute 'current_device'

In [7]:
torch.device('cpu')

device(type='cpu')

In [9]:
x =torch.rand((10,3))

In [10]:
x[0]

tensor([0.8564, 0.2552, 0.8705])

In [11]:
ref = torch.rand(1,3)

In [12]:
x - ref

tensor([[ 0.7118, -0.1973,  0.4388],
        [ 0.0900,  0.5144,  0.4334],
        [ 0.3662,  0.1302,  0.4984],
        [ 0.3605, -0.2682, -0.4023],
        [ 0.4175,  0.5001, -0.3299],
        [ 0.4785, -0.3132, -0.4084],
        [ 0.5098, -0.0322,  0.1477],
        [-0.0243,  0.5328,  0.1293],
        [ 0.2912,  0.2004,  0.5180],
        [ 0.7245,  0.1096,  0.2939]])

In [20]:
torch.sqrt(torch.sum(torch.pow(x-ref,2),axis=1,keepdim=True))

tensor([[0.8592],
        [0.6786],
        [0.6320],
        [0.6031],
        [0.7303],
        [0.7027],
        [0.5317],
        [0.5488],
        [0.6271],
        [0.7895]])

In [23]:
len(torch.empty(0))

0

In [32]:
x = {'one' : 1, 'two' :2}

In [34]:
for key,value  in x.items():
    print(key) 

one
two


In [35]:
test = torch.empty(0)

In [37]:
test.append(3)

AttributeError: 'Tensor' object has no attribute 'append'

In [39]:
test = torch.cat((test,3.),dim=0)

TypeError: expected Tensor as element 1 in argument 0, but got float

In [40]:
yada = [3,2,3,4]

In [41]:
torch.Tensor(yada)

tensor([3., 2., 3., 4.])

In [42]:
x

{'one': 1, 'two': 2}

In [46]:
x.values()

dict_values([1, 2])

In [48]:
torch.Tensor(x.values())

TypeError: new(): data must be a sequence (got dict_values)

In [66]:
x2.shape[0]

10000

In [65]:
if len(x2.shape) is 2:
    print("ya")

ya


In [68]:
x1.shape

torch.Size([10000, 3])

In [71]:
f(x1,x2).shape[0]

10000