In [1]:
import os
home = os.getenv("HOME")
os.chdir(home+"/codes/pymfree/")

In [2]:
import torch
import numpy as np
import sklearn
import faiss
from sklearn.neighbors import DistanceMetric
from pymfree.util.utils import any_norm_nn_search
from pymfree.core.function import Norm
from pymfree.core.function import L2Norm
from pymfree.core.function import L2SquaredNorm
from pymfree.util.functional import l2l2

## Norm Definitions and Timing

In [3]:
x1 = torch.rand(100000,3)
x2 = torch.rand(100000,3)
x3 = np.random.rand(100000,3)
x4 = np.random.rand(100000,3)

In [4]:
len(x1.shape)

2

In [5]:
%%time
result = F.l2(x1)

CPU times: user 2.09 ms, sys: 3.65 ms, total: 5.74 ms
Wall time: 1.83 ms


In [6]:
%%time 
result = F.l2(x1-x2)

CPU times: user 5.38 ms, sys: 0 ns, total: 5.38 ms
Wall time: 1.24 ms


In [7]:
l2_skl = DistanceMetric.get_metric('euclidean')
point = [0.,0.,0.]
ref = np.empty((1,3))
ref[0] = point

In [8]:
%%time 
result = l2_skl.pairwise(x3-x4,ref)

CPU times: user 2.93 ms, sys: 627 µs, total: 3.56 ms
Wall time: 2.73 ms


In [9]:
my_norm = L2Norm()

In [10]:
%%time
result = my_norm.NoChecksPair(x1,x2)

CPU times: user 4.36 ms, sys: 815 µs, total: 5.17 ms
Wall time: 1.12 ms


In [11]:
type(result)

torch.Tensor

In [12]:
%%time
my_norm.array_out = True
result = my_norm(x3,x4)

CPU times: user 17.6 ms, sys: 0 ns, total: 17.6 ms
Wall time: 4.18 ms


In [13]:
metric = sklearn.neighbors.DistanceMetric.get_metric('pyfunc',func=my_norm.sklearn_dist)

In [14]:
%%time
result = metric.pairwise(x3-x4, ref)

CPU times: user 4.25 s, sys: 0 ns, total: 4.25 s
Wall time: 4.25 s


In [19]:
result

array([[0.6762106 ],
       [0.48675421],
       [0.66289467],
       ...,
       [0.81493543],
       [0.86552196],
       [0.50522523]])

In [16]:
my_norm.sklearn_dist(x1,ref)

TypeError: PyMFree Norm: Need torch Tensor of shape (n,d).

In [17]:
x5 = np.random.rand(3)
x6 = np.random.rand(3)

In [18]:
my_norm.sklearn_dist(x5,x6)

array(1.05026461)

In [22]:
isinstance(my_norm, L2Norm)

True

In [23]:
x = torch.rand(10,10,10)

In [28]:
for line in x:
    print(line.shape)

torch.Size([10, 10])
torch.Size([10, 10])
torch.Size([10, 10])
torch.Size([10, 10])
torch.Size([10, 10])
torch.Size([10, 10])
torch.Size([10, 10])
torch.Size([10, 10])
torch.Size([10, 10])
torch.Size([10, 10])


In [15]:
def test_f(x):
    return x.shape

In [22]:
try:
    test_f(torch.rand(10), torch.rand(8))
except Exception as e:
    print(e)

test_f() takes 1 positional argument but 2 were given


In [8]:
r = torch.rand(10)

In [9]:
torch.exp(-torch.pow(r, 2))

tensor([0.5141, 0.9239, 0.9965, 0.9999, 0.5335, 0.9941, 0.4266, 0.5710, 0.9744,
        0.4943])

In [11]:
torch.tensor(0).shape

torch.Size([])

In [12]:
mine = {'test' : 1, 'test2' : 2.}

In [13]:
mine

{'test': 1, 'test2': 2.0}

In [14]:
mine.values()

dict_values([1, 2.0])

In [ ]:
for key, x in mine.values()


In [16]:
test3 =[]
test4= []

In [33]:
test3, test4 = zip(*[(key,x) for key, x in mine.items()])

In [21]:
for key, value in mine.values():
    print(key)

TypeError: cannot unpack non-iterable int object

In [22]:
mine

{'test': 1, 'test2': 2.0}

In [24]:
test3

[1, 2.0]

In [29]:
test3

('test', 1)

In [35]:
test4

(1, 2.0)

In [37]:
type(torch.device('cpu'))

torch.device

In [38]:
x = torch.rand(30)

In [40]:
x = x.to(torch.device('cpu'))

In [41]:
x

tensor([0.7993, 0.6759, 0.2407, 0.9368, 0.2786, 0.1179, 0.2627, 0.7775, 0.9536,
        0.2038, 0.8492, 0.4192, 0.5474, 0.7776, 0.8183, 0.5241, 0.6989, 0.6648,
        0.8443, 0.1373, 0.1285, 0.0577, 0.5034, 0.8627, 0.2614, 0.9515, 0.9469,
        0.5260, 0.6852, 0.3917])

In [42]:
x.device

device(type='cpu')

In [45]:
class fake_class(object):
    def __init__(self):
        self.name = self.__class__.__name__

    def __str__(self):
        return str(self.name)
    def __repr__(self):
        print(self)

In [46]:
my_class = fake_class

In [47]:
print(fake_class)

<class '__main__.fake_class'>


In [57]:
x = fake_class

In [50]:
def my_func():
    return 4

In [54]:
my_func.__class__.__name__

'function'

In [55]:
x =str(my_func)[]

In [56]:
x

'<function my_func at 0x7fdfca07f680>'

In [61]:
x = str(x)

In [62]:
type(x)

str

In [70]:
one = x[x.rfind('.')+1:x.rfind('\'')]

In [71]:
two = str(my_func).split(' ')[1]

In [76]:
final = one + "\n\n" +two

In [77]:
print(final)

fake_class

my_func


In [78]:
test = {'one' : 1, 'two' : 2}

In [79]:
str(test)

"{'one': 1, 'two': 2}"

In [80]:
test.values()

dict_values([1, 2])

In [81]:
x = list(test.values())
y = list(test.keys())

In [82]:
x

[1, 2]

In [86]:
x2 = torch.rand(2)

In [84]:
y = t

['one', 'two']

In [88]:
{key: value for (key,value) in zip(y,x2)}

{'one': tensor(0.2945), 'two': tensor(0.9416)}

In [89]:
isinstance(x2, torch.Tensor)

True

In [91]:
isinstance(y, list)

True

In [103]:
test = list(range(20))

In [100]:
test

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [101]:
test.shape

AttributeError: 'list' object has no attribute 'shape'

In [104]:
test = np.array(test)

In [105]:
test

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [107]:
len(test)%3

2

In [113]:
test[:-(len(test)%3)].reshape(-1,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [128]:
coordinates = np.arange(20)
dim=3

In [129]:
node_coordinates = torch.tensor(coordinates)[
                :-(len(coordinates) % dim)].reshape(-1,dim)

In [130]:
node_coordinates

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])

In [123]:
torch.tensor(node_coordinates)

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])

In [131]:
node_coordinates.dtype

torch.int64

In [132]:
len(None)

TypeError: object of type 'NoneType' has no len()

In [1]:
import faiss
import torch
import sklearn
from sklearn.neighbors import KDTree

In [2]:
coordinates = torch.rand(100000,3)
query = torch.rand(100000,3)
k = 32

In [5]:
%%time
index1 = faiss.IndexFlat(3)
index1.add(coordinates.numpy())

CPU times: user 3.57 ms, sys: 0 ns, total: 3.57 ms
Wall time: 3.13 ms


In [7]:
%%time
index2 = KDTree(coordinates)

CPU times: user 98.6 ms, sys: 0 ns, total: 98.6 ms
Wall time: 97.2 ms


In [9]:
%%time
x1, d1= index1.search(query.numpy(),k)

CPU times: user 41.8 s, sys: 120 ms, total: 41.9 s
Wall time: 10.5 s


In [10]:
%%time
x2, d2 = index2.query(query,k)

CPU times: user 1.69 s, sys: 32 ms, total: 1.72 s
Wall time: 1.72 s


In [39]:
x1

array([[8.2731247e-05, 2.7394295e-04, 3.7622452e-04, ..., 1.9688606e-03,
        2.0182133e-03, 2.0627975e-03],
       [3.3664703e-04, 4.6634674e-04, 4.8971176e-04, ..., 1.7213821e-03,
        1.7743111e-03, 1.8014908e-03],
       [2.4986267e-04, 3.0303001e-04, 5.3858757e-04, ..., 1.8742085e-03,
        1.9509792e-03, 2.0077229e-03],
       ...,
       [1.3041496e-04, 5.3596497e-04, 6.0832500e-04, ..., 2.2336245e-03,
        2.2453070e-03, 2.3525953e-03],
       [3.1948090e-05, 2.1600723e-04, 2.6130676e-04, ..., 1.6522408e-03,
        1.6646385e-03, 1.7936230e-03],
       [5.3763390e-05, 8.2015991e-05, 1.1730194e-04, ..., 1.4933348e-03,
        1.5386343e-03, 1.7747879e-03]], dtype=float32)

In [40]:
x2

array([[0.0091032 , 0.01654602, 0.01939925, ..., 0.04437368, 0.04492363,
        0.04541758],
       [0.01835218, 0.02159179, 0.02212849, ..., 0.04148451, 0.04212629,
        0.04244359],
       [0.01580528, 0.01740968, 0.0232074 , ..., 0.04329294, 0.04417083,
        0.04480761],
       ...,
       [0.01141704, 0.02315022, 0.02466356, ..., 0.04726098, 0.047384  ,
        0.04850485],
       [0.00564214, 0.0147009 , 0.01616   , ..., 0.04064754, 0.04079976,
        0.04235285],
       [0.00733661, 0.00905695, 0.01082708, ..., 0.03864441, 0.03922567,
        0.04212815]])

In [41]:
0.0091032*0.0091032

8.286825024e-05

In [42]:
0.01654602*0.01654602

0.00027377077784040006

In [43]:
isinstance(32,int)

True

In [44]:
coorindates

NameError: name 'coorindates' is not defined

In [45]:
coordinates

tensor([[0.7387, 0.5248, 0.1141],
        [0.6848, 0.2159, 0.9854],
        [0.2157, 0.0270, 0.9292],
        ...,
        [0.7772, 0.4445, 0.6965],
        [0.3244, 0.6095, 0.5106],
        [0.2248, 0.9851, 0.0596]])

In [49]:
torch.max(coordinates,axis=0).values

tensor([1.0000, 1.0000, 1.0000])

In [52]:
testy = torch.rand(100,3)

In [60]:
torch.max(testy, axis=0).values - torch.min(testy, axis=0).values

tensor([0.9960, 0.9935, 0.9908])

In [11]:
from sklearn.preprocessing import MinMaxScaler

In [62]:
torch.argmax(torch.max(testy, axis=0).values - torch.min(testy, axis=0).values).item()

0

In [63]:
scaler = MinMaxScaler(feature_range=(-1,1))

In [64]:
scaler.fit(testy[:,0].unsqueeze(axis=1))

MinMaxScaler(copy=True, feature_range=(-1, 1))

In [19]:
testy[:,2].shape

torch.Size([100])

In [26]:
testy[:,2].unsqueeze(axis=1).shape

torch.Size([100, 1])

In [30]:
scaler.transform(testy[:,0].unsqueeze(axis=1))

array([[-0.7484512 ],
       [ 0.80935302],
       [ 0.80633725],
       [ 0.61013382],
       [ 0.55643945],
       [-0.82030287],
       [ 0.37811058],
       [-0.8877782 ],
       [ 0.20858997],
       [-0.40721845],
       [ 0.87775237],
       [ 0.42590619],
       [ 0.97285914],
       [ 0.88276156],
       [-0.79016833],
       [ 0.99472534],
       [ 0.05617753],
       [-0.64435595],
       [ 0.59745589],
       [-0.28482926],
       [-0.65696304],
       [ 0.80029622],
       [-0.70243878],
       [-0.69511379],
       [-0.50123864],
       [-0.26313631],
       [ 0.90416071],
       [ 0.40761694],
       [-0.13436463],
       [ 0.29494262],
       [-0.49820438],
       [ 0.54227717],
       [-0.14794953],
       [-0.3805899 ],
       [ 0.38502195],
       [ 0.59041064],
       [ 0.65227934],
       [-0.07118459],
       [ 0.97324142],
       [ 1.00891224],
       [-0.63308769],
       [ 0.1057585 ],
       [-0.38656862],
       [-0.6233123 ],
       [-0.90599493],
       [-0

In [32]:
torch.tensor([0.])

tensor([0.])

In [34]:
coordinates.__class__.__name__

'Tensor'

In [38]:
type(index1)

faiss.swigfaiss_avx2.IndexFlat

In [39]:
str(type(index1))

"<class 'faiss.swigfaiss_avx2.IndexFlat'>"

In [41]:
str(index1.__class__.__name__)

'IndexFlat'

In [44]:
None.__class__.__name__

'NoneType'

In [47]:
str(scaler.get_params()['feature_range'])

'(-1, 1)'

In [50]:
scaler =MinMaxScaler(feature_range=(-10,1))

In [51]:
scaler

MinMaxScaler(copy=True, feature_range=(-10, 1))

In [67]:
for x in testy.T:
    print(x.shape)

torch.Size([100])
torch.Size([100])
torch.Size([100])


In [66]:
testy.shape

torch.Size([100, 3])

In [51]:
def nn(query, support, norm, num=32):
    n = len(query)
    m = len(support)
    result = torch.zeros(n,num,dtype=torch.float32)
    indices = torch.zeros(n,num,dtype=torch.int64)
    for i, element in enumerate(query):
        current = torch.sub(support, element)
        current = norm.no_checks(current)
        dists, numbers = torch.sort(current)
        result[i,:] = dists[:num]
        indices[i,:] = numbers[:num]
    return result, indices

In [3]:
query = torch.rand(10000,3)
support = torch.rand(10000,3)
norm = L2SquaredNorm()

In [4]:
isinstance(norm, L2Norm)

False

In [4]:
l2l2()

NameError: name 'l2l2' is not defined

In [4]:
%%time
one, two = any_norm_nn_search(support,query, norm)

CPU times: user 15.2 s, sys: 7.2 ms, total: 15.2 s
Wall time: 14.6 s


In [5]:
index = faiss.IndexFlatL2(3) 

In [6]:
index.add(support.numpy())

In [7]:
%%time
index.search(query.numpy(),k=32)

CPU times: user 819 ms, sys: 28.2 ms, total: 847 ms
Wall time: 214 ms


(array([[7.12394714e-04, 1.47819519e-03, 1.73604488e-03, ...,
         1.00859404e-02, 1.06242895e-02, 1.13196373e-02],
        [1.00255013e-04, 2.63452530e-04, 4.69088554e-04, ...,
         8.92508030e-03, 8.94713402e-03, 9.19294357e-03],
        [6.72340393e-05, 6.58273697e-04, 1.60098076e-03, ...,
         8.37039948e-03, 8.51607323e-03, 9.53865051e-03],
        ...,
        [8.52584839e-04, 2.23302841e-03, 2.24542618e-03, ...,
         1.00972652e-02, 1.01251602e-02, 1.04300976e-02],
        [1.05667114e-03, 1.20282173e-03, 1.42908096e-03, ...,
         7.65085220e-03, 8.37469101e-03, 8.38136673e-03],
        [1.07288361e-04, 7.26938248e-04, 7.29084015e-04, ...,
         8.45026970e-03, 8.61835480e-03, 8.66651535e-03]], dtype=float32),
 array([[3777, 4672, 5418, ...,  797, 2311, 9591],
        [9014, 9782, 9830, ..., 5273, 8815, 8298],
        [7307, 9046, 3483, ...,  707, 5898, 5103],
        ...,
        [3804, 7107, 1709, ..., 1542, 5152, 3953],
        [6469, 5316, 9294, ..., 7

In [9]:
one

tensor([[7.1223e-04, 1.4780e-03, 1.7360e-03,  ..., 1.0086e-02, 1.0624e-02,
         1.1320e-02],
        [1.0039e-04, 2.6350e-04, 4.6907e-04,  ..., 8.9252e-03, 8.9472e-03,
         9.1929e-03],
        [6.7223e-05, 6.5814e-04, 1.6011e-03,  ..., 8.3704e-03, 8.5162e-03,
         9.5385e-03],
        ...,
        [8.5230e-04, 2.2328e-03, 2.2453e-03,  ..., 1.0097e-02, 1.0125e-02,
         1.0430e-02],
        [1.0567e-03, 1.2029e-03, 1.4292e-03,  ..., 7.6509e-03, 8.3749e-03,
         8.3814e-03],
        [1.0733e-04, 7.2694e-04, 7.2927e-04,  ..., 8.4504e-03, 8.6183e-03,
         8.6667e-03]])

In [58]:
norm = L2Norm()

In [59]:
isinstance(norm, Norm)

True

In [8]:
l2l2(torch.rand(1,1), torch.rand(1,1))

tensor([0.6226])