In [1]:
import os
home = os.getenv("HOME")
os.chdir(home+"/codes/pymfree/")

In [2]:
import itertools
import numpy as np
import torch
from pymfree.util.polynomial import get_poynomials

In [10]:
%%time
get_poynomials(3,7)

CPU times: user 4.7 ms, sys: 0 ns, total: 4.7 ms
Wall time: 3.68 ms


tensor([[0, 0, 0],
        [1, 0, 0],
        [0, 1, 0],
        [0, 0, 1],
        [2, 0, 0],
        [1, 1, 0],
        [1, 0, 1],
        [0, 2, 0],
        [0, 1, 1],
        [0, 0, 2],
        [3, 0, 0],
        [2, 1, 0],
        [2, 0, 1],
        [1, 2, 0],
        [1, 1, 1],
        [1, 0, 2],
        [0, 3, 0],
        [0, 2, 1],
        [0, 1, 2],
        [0, 0, 3],
        [4, 0, 0],
        [3, 1, 0],
        [3, 0, 1],
        [2, 2, 0],
        [2, 1, 1],
        [2, 0, 2],
        [1, 3, 0],
        [1, 2, 1],
        [1, 1, 2],
        [1, 0, 3],
        [0, 4, 0],
        [0, 3, 1],
        [0, 2, 2],
        [0, 1, 3],
        [0, 0, 4],
        [5, 0, 0],
        [4, 1, 0],
        [4, 0, 1],
        [3, 2, 0],
        [3, 1, 1],
        [3, 0, 2],
        [2, 3, 0],
        [2, 2, 1],
        [2, 1, 2],
        [2, 0, 3],
        [1, 4, 0],
        [1, 3, 1],
        [1, 2, 2],
        [1, 1, 3],
        [1, 0, 4],
        [0, 5, 0],
        [0, 4, 1],
        [0, 

In [70]:
dims = torch.tensor([0,1,2])
p = 3

In [137]:
out = torch.combinations(dims,with_replacement=True,r=3)

In [138]:
out

tensor([[0, 0, 0],
        [0, 0, 1],
        [0, 0, 2],
        [0, 1, 1],
        [0, 1, 2],
        [0, 2, 2],
        [1, 1, 1],
        [1, 1, 2],
        [1, 2, 2],
        [2, 2, 2]])

In [133]:
one = (out==0).sum(axis=1)
two = (out==1).sum(axis=1)
three = torch.stack([one,two],1)
print(one)
print(two)
print(three)

tensor([2, 1, 1, 0, 0, 0])
tensor([0, 1, 0, 2, 1, 0])
tensor([[2, 0],
        [1, 1],
        [1, 0],
        [0, 2],
        [0, 1],
        [0, 0]])


In [ ]:
def convert_terms(terms,dims):
    out = torch.zeros([len(terms),len(dims)],dtype=torch.int64)
    for i,term in enumerate(terms):
        for j, dim in enumerate(dims):
            out[i,j] = (term==dim).sum()
    return out

In [154]:
def convert_terms_faster(terms,dims):
    stack=[]
    for dim in dims:
        stack.append((terms==dim).sum(axis=1))
    return torch.stack(stack,1)

In [165]:
%%time
out_old = convert_terms(out,dims)

CPU times: user 2.97 ms, sys: 0 ns, total: 2.97 ms
Wall time: 2.35 ms


In [156]:
out_old

tensor([[3, 0, 0],
        [2, 1, 0],
        [2, 0, 1],
        [1, 2, 0],
        [1, 1, 1],
        [1, 0, 2],
        [0, 3, 0],
        [0, 2, 1],
        [0, 1, 2],
        [0, 0, 3]])

In [167]:
%%time
out_faster = convert_terms_faster(out,dims)

CPU times: user 1.73 ms, sys: 56 µs, total: 1.79 ms
Wall time: 1.02 ms


In [162]:
out_faster

tensor([[3, 0, 0],
        [2, 1, 0],
        [2, 0, 1],
        [1, 2, 0],
        [1, 1, 1],
        [1, 0, 2],
        [0, 3, 0],
        [0, 2, 1],
        [0, 1, 2],
        [0, 0, 3]])

In [168]:
%%time
out = torch.zeros(1,3,dtype=torch.int64)
for i in range(1,p+1):
    out = torch.cat((out, convert_terms(torch.combinations(dims,with_replacement=True,r=i),dims)))
# print(out)

CPU times: user 3.77 ms, sys: 0 ns, total: 3.77 ms
Wall time: 3 ms


In [169]:
out.shape

torch.Size([20, 3])

In [84]:
out2

tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])

In [170]:
out

tensor([[0, 0, 0],
        [1, 0, 0],
        [0, 1, 0],
        [0, 0, 1],
        [2, 0, 0],
        [1, 1, 0],
        [1, 0, 1],
        [0, 2, 0],
        [0, 1, 1],
        [0, 0, 2],
        [3, 0, 0],
        [2, 1, 0],
        [2, 0, 1],
        [1, 2, 0],
        [1, 1, 1],
        [1, 0, 2],
        [0, 3, 0],
        [0, 2, 1],
        [0, 1, 2],
        [0, 0, 3]])

In [11]:
len(out)

20

In [12]:
torch.tensor()

TypeError: tensor() missing 1 required positional arguments: "data"

In [28]:
x = torch.zeros(10) +2.
exp = torch.range(0,9)

In [29]:
torch.pow(x,exp)

tensor([  1.,   2.,   4.,   8.,  16.,  32.,  64., 128., 256., 512.])

In [26]:
exp

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [67]:
exps = get_poynomials(3,2)
coords = torch.rand(10000,1,32,3)

In [51]:
exps

tensor([[0, 0, 0],
        [1, 0, 0],
        [0, 1, 0],
        [0, 0, 1],
        [2, 0, 0],
        [1, 1, 0],
        [1, 0, 1],
        [0, 2, 0],
        [0, 1, 1],
        [0, 0, 2]])

In [68]:
print(coords.shape)
print(exps.shape)

torch.Size([10000, 1, 32, 3])
torch.Size([10, 3])


In [31]:
torch.pow(coords,exps[0]).shape

torch.Size([10, 32, 3])

In [79]:
%%time
out = []
for exp in exps:
    out.append(torch.pow(coords,exp).prod(3,keepdim=True))
out = torch.cat(out,3)

CPU times: user 567 ms, sys: 183 µs, total: 567 ms
Wall time: 142 ms


In [80]:
out.shape

torch.Size([10000, 1, 32, 10])

In [63]:
out

tensor([[[[1.0000e+00, 6.7512e-01, 7.3473e-02,  ..., 5.3983e-03,
           6.1193e-02, 6.9366e-01],
          [1.0000e+00, 9.9886e-01, 5.9526e-01,  ..., 3.5434e-01,
           5.4483e-01, 8.3774e-01],
          [1.0000e+00, 2.6086e-01, 9.8458e-01,  ..., 9.6940e-01,
           8.8389e-01, 8.0593e-01],
          ...,
          [1.0000e+00, 5.5156e-01, 5.3207e-01,  ..., 2.8310e-01,
           2.6553e-02, 2.4906e-03],
          [1.0000e+00, 4.2578e-01, 5.7054e-01,  ..., 3.2551e-01,
           1.2392e-01, 4.7173e-02],
          [1.0000e+00, 8.4160e-02, 7.2084e-01,  ..., 5.1961e-01,
           1.8864e-01, 6.8486e-02]]],


        [[[1.0000e+00, 9.4248e-01, 7.1668e-01,  ..., 5.1363e-01,
           3.4564e-01, 2.3259e-01],
          [1.0000e+00, 8.0411e-01, 2.4531e-01,  ..., 6.0179e-02,
           1.0513e-01, 1.8365e-01],
          [1.0000e+00, 5.6800e-01, 5.3039e-01,  ..., 2.8132e-01,
           3.7583e-01, 5.0208e-01],
          ...,
          [1.0000e+00, 9.6016e-01, 1.8771e-01,  ..., 3.52

In [73]:
exps

tensor([[0, 0, 0],
        [1, 0, 0],
        [0, 1, 0],
        [0, 0, 1],
        [2, 0, 0],
        [1, 1, 0],
        [1, 0, 1],
        [0, 2, 0],
        [0, 1, 1],
        [0, 0, 2]])

In [74]:
for row in exps:
    print(row.shape)

torch.Size([3])
torch.Size([3])
torch.Size([3])
torch.Size([3])
torch.Size([3])
torch.Size([3])
torch.Size([3])
torch.Size([3])
torch.Size([3])
torch.Size([3])


In [86]:
torch.max(get_poynomials(3,3)).item()

3

In [97]:
AP = torch.zeros(10,1,10,10)

In [98]:
AP_insert = torch.rand(10,1,5,5)

In [99]:
AP[:,:,:5,5:] = AP_insert

In [100]:
AP

tensor([[[[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0766, 0.1811, 0.6857,
           0.2064, 0.6717],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0160, 0.7451, 0.7629,
           0.8362, 0.6902],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.9466, 0.7726, 0.6191,
           0.3034, 0.2792],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.5481, 0.6838, 0.7095,
           0.2833, 0.1053],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.6863, 0.3665, 0.7793,
           0.7667, 0.2129],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000