In [1]:
import os
home = os.getenv("HOME")
os.chdir(home+"/codes/pymfree/")

In [2]:
import torch 
import numpy as np
from pymfree.util.utils import insert_A_in_AP_matrix
from pymfree.util.utils import asymmetric_distances
from pymfree.util.utils import symmetrise_AP
from pymfree.core.function import L2Norm

In [3]:
norm = L2Norm()

In [4]:
x = torch.rand(10,1,4,3)

In [5]:
diff = asymmetric_distances(x)

In [7]:
diff.shape

torch.Size([10, 1, 6, 3])

In [10]:
diff.reshape(-1).shape

torch.Size([180])

In [7]:
scalar = norm(diff) 

In [8]:
scalar

tensor([1.1103, 0.8469, 0.7919, 0.9898, 0.3244, 0.8087])

In [9]:
my_try = torch.rand(2,1,6)

In [14]:
my_try

tensor([[[0.8491, 0.2638, 0.6330, 0.4111, 0.2552, 0.8317]],

        [[0.4687, 0.4466, 0.9155, 0.0923, 0.0989, 0.8026]]])

In [11]:
AP = torch.zeros(2,1,8,8)

In [12]:
AP = insert_A_in_AP_matrix(my_try,AP,4)

torch.Size([2, 1, 3])
torch.Size([2, 1, 3]) 0 3
torch.Size([2, 1, 2])
torch.Size([2, 1, 2]) 3 5
torch.Size([2, 1, 1])
torch.Size([2, 1, 1]) 5 6


In [13]:
AP

tensor([[[[0.0000, 0.8491, 0.2638, 0.6330, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.4111, 0.2552, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.8317, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000]]],


        [[[0.0000, 0.4687, 0.4466, 0.9155, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0923, 0.0989, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.8026, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        

In [16]:
AP = AP + AP.transpose(2,3)

In [17]:
AP

tensor([[[[0.0000, 0.8491, 0.2638, 0.6330, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.8491, 0.0000, 0.4111, 0.2552, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.2638, 0.4111, 0.0000, 0.8317, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.6330, 0.2552, 0.8317, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000]]],


        [[[0.0000, 0.4687, 0.4466, 0.9155, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.4687, 0.0000, 0.0923, 0.0989, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.4466, 0.0923, 0.0000, 0.8026, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.9155, 0.0989, 0.8026, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        

In [17]:
timeing = torch.rand(10000,1,32,3)

In [38]:
%%time
out = torch.pow(timeing,2)

CPU times: user 6.9 ms, sys: 297 µs, total: 7.2 ms
Wall time: 2.3 ms


In [39]:
%%time
out = []
for i in range(100):
    out.append(torch.pow(timeing[i,0,:,:],2))
out = torch.stack(out).unsqueeze(1)

CPU times: user 9.69 ms, sys: 71 µs, total: 9.76 ms
Wall time: 7.18 ms


In [31]:
out.shape

torch.Size([100, 1, 32, 3])

In [6]:
newx = torch.rand(10,1,10,3)

In [7]:
newx[:,:,0:1] - newx[:,:,1:]

tensor([[[[-0.0576,  0.3204, -0.4223],
          [ 0.0816, -0.3339, -0.8451],
          [ 0.1656, -0.3345, -0.2682],
          [ 0.5215,  0.2270, -0.8511],
          [-0.2540, -0.3154, -0.1476],
          [ 0.0442, -0.4684, -0.3170],
          [ 0.1111,  0.1225, -0.3551],
          [ 0.2815,  0.1587, -0.2181],
          [-0.2793,  0.2973, -0.2141]]],


        [[[ 0.7573,  0.6412, -0.1278],
          [ 0.1225, -0.2664, -0.1732],
          [-0.1381, -0.0250,  0.2396],
          [ 0.3205, -0.0775, -0.7031],
          [ 0.1957,  0.3311,  0.1838],
          [ 0.2961, -0.1205, -0.6274],
          [ 0.3403,  0.6015,  0.0732],
          [ 0.5638, -0.2678, -0.3201],
          [ 0.6781,  0.2692, -0.0844]]],


        [[[-0.0727,  0.4464, -0.1176],
          [-0.4191, -0.1918, -0.3652],
          [-0.9419,  0.1777,  0.0230],
          [ 0.0123, -0.3120, -0.3108],
          [-0.2220, -0.1711,  0.4222],
          [-0.2799,  0.0845, -0.3527],
          [-0.8233, -0.3888, -0.1663],
          [-0.245

In [49]:
newx[:,0,0:1,:].shape

torch.Size([10, 1, 3])

In [48]:
newx[:,0,1:,:].shape

torch.Size([10, 9, 3])

In [11]:
coordinates = torch.rand(10,3)

In [12]:
indeces = torch.randint(10,(10,10))

In [13]:
indeces

tensor([[2, 6, 4, 5, 2, 0, 0, 1, 0, 8],
        [8, 0, 4, 3, 8, 7, 0, 4, 1, 9],
        [9, 0, 9, 2, 4, 1, 0, 4, 8, 8],
        [1, 6, 6, 5, 6, 2, 3, 0, 9, 8],
        [4, 9, 3, 0, 1, 0, 2, 1, 5, 2],
        [4, 5, 1, 6, 7, 8, 1, 3, 4, 0],
        [6, 4, 2, 5, 8, 9, 9, 4, 2, 0],
        [4, 2, 7, 2, 9, 1, 0, 7, 5, 3],
        [1, 0, 6, 2, 5, 5, 5, 9, 8, 7],
        [5, 9, 9, 1, 9, 0, 2, 0, 0, 2]])

In [17]:
coordinates[8]

tensor([0.6212, 0.5242, 0.7471])

In [14]:
coordinates[indeces]

tensor([[[9.7161e-01, 5.6219e-01, 8.1246e-01],
         [6.7323e-01, 8.3049e-01, 2.3087e-01],
         [7.2437e-01, 1.8942e-01, 6.0114e-01],
         [1.5602e-01, 9.9132e-01, 7.5928e-01],
         [9.7161e-01, 5.6219e-01, 8.1246e-01],
         [4.8044e-01, 2.0337e-01, 5.8587e-01],
         [4.8044e-01, 2.0337e-01, 5.8587e-01],
         [7.8971e-01, 8.0188e-01, 1.1340e-01],
         [4.8044e-01, 2.0337e-01, 5.8587e-01],
         [6.2123e-01, 5.2423e-01, 7.4708e-01]],

        [[6.2123e-01, 5.2423e-01, 7.4708e-01],
         [4.8044e-01, 2.0337e-01, 5.8587e-01],
         [7.2437e-01, 1.8942e-01, 6.0114e-01],
         [1.0905e-01, 2.6029e-04, 3.3363e-01],
         [6.2123e-01, 5.2423e-01, 7.4708e-01],
         [8.4762e-01, 7.2292e-01, 7.9634e-01],
         [4.8044e-01, 2.0337e-01, 5.8587e-01],
         [7.2437e-01, 1.8942e-01, 6.0114e-01],
         [7.8971e-01, 8.0188e-01, 1.1340e-01],
         [7.7508e-01, 8.3921e-01, 4.0363e-01]],

        [[7.7508e-01, 8.3921e-01, 4.0363e-01],
         

In [20]:
torch.get_default_tensor_type()

AttributeError: module 'torch' has no attribute 'get_default_tensor_type'

In [21]:
torch.cuda.FloatTensor

torch.cuda.FloatTensor

In [22]:
type(torch.device('cpu'))

torch.device

In [25]:
type(x.device)

torch.device

In [46]:
list = ['one', 'two', 'three']
query = 'three'

In [50]:
indeces = [i for i, word in enumerate(list) if word == query]

In [48]:
indeces

[2]

In [31]:
isinstance(query, str)

False

In [32]:
test = torch.rand(4)

In [33]:
values = [4.3,3.4]

In [34]:
indx = [0,3]

In [37]:
test[indx] = torch.tensor(values)

In [38]:
test

tensor([4.3000, 0.2429, 0.0997, 3.4000])

In [51]:
test[indeces] = 4.5

In [52]:
test

tensor([4.3000, 0.2429, 4.5000, 3.4000])

In [54]:
str(test[0].item())

'4.300000190734863'

In [55]:
test.to(torch.device('cpu'))

tensor([4.3000, 0.2429, 4.5000, 3.4000])

In [56]:
torch.to(test,torch.device('cpu'))

AttributeError: module 'torch' has no attribute 'to'

In [4]:
np.random.rand(10,3)

array([[0.26949575, 0.35836919, 0.19105091],
       [0.76984487, 0.66057096, 0.29151179],
       [0.92544005, 0.2203059 , 0.41525836],
       [0.64671806, 0.72740072, 0.07899761],
       [0.48486077, 0.04440498, 0.79555028],
       [0.71290384, 0.78598254, 0.13961501],
       [0.96916291, 0.84814261, 0.90211771],
       [0.4955048 , 0.19944255, 0.94577919],
       [0.48913701, 0.30499959, 0.87072803],
       [0.72558112, 0.61545471, 0.22941455]])

In [5]:
from pymfree.util.functional import l2

In [12]:
str(l2.__name__)

'l2'

In [7]:
myl2 = l2()

TypeError: l2() missing 1 required positional argument: 'x'

In [20]:
L2Norm??

Init signature: L2Norm(numpy=False)
Source:        
class L2Norm(Norm):
    r""" A fast-lane implementation of the l2-norm.

    This inherits from Norm and delivers the l2-norm by simply calling
    the general constructor with fixed function l2.

    Parameters
    ----------
    numpy : bool, optional
        Falg indication if the output shall be a numpy array instead of a
        torch tensor. Default to False.


    See also
    --------
    pymfree.core.function.Norm

    References
    ----------
    [1] [L2-Norm on Wolfram](https://mathworld.wolfram.com/L2-Norm.html)
    r"""
    def __init__(self, numpy=False):
        super().__init__(l2, numpy)
File:           ~/codes/pymfree/pymfree/core/function.py
Type:           type
Subclasses:     
